MythicIsland_IslandEntrance_MapScripts::
	.byte 0


# 3 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
teleportSpin:
# 4 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_left
# 5 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_16
# 6 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_up
# 7 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_16
# 8 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_right
# 9 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_16
# 10 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_down
# 11 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_left
# 12 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_8
# 13 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_up
# 14 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_8
# 15 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_right
# 16 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_8
# 17 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_down
# 18 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_left
# 19 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_4
# 20 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_up
# 21 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_4
# 22 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_right
# 23 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_4
# 24 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_down
# 25 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_left
# 26 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 27 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_up
# 28 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 29 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_right
# 30 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 31 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_down
# 32 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 33 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_left
# 34 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 35 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_up
# 36 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 37 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_right
# 38 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 39 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_down
# 40 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 41 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_left
# 42 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 43 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_up
# 44 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 45 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_right
# 46 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 47 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_down
# 48 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 49 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_left
# 50 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 51 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_up
# 52 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 53 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_right
# 54 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 55 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_down
# 56 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 57 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_left
# 58 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 59 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_up
# 60 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 61 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_right
# 62 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 63 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_down
# 64 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 65 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_left
# 66 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 67 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_up
# 68 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	delay_2
# 69 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_player
# 70 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	step_end

# 73 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
teleportFly:
# 74 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	face_up
# 75 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	disable_anim
# 76 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	slide_up
# 77 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	slide_up
# 78 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	slide_up
# 79 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	slide_up
# 80 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	slide_up
# 81 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	slide_up
# 82 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	step_end

MythicIsland_IslandEntrance_Sign::
# 87 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_Sign_Text_0, MSGBOX_SIGN
	return


MythicIsland_IslandEntrance_EnterBoat::
# 94 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	lock
# 95 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_EnterBoat_Text_0, MSGBOX_YESNO
# 98 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	compare VAR_RESULT, YES
	goto_if_eq MythicIsland_IslandEntrance_EnterBoat_2
MythicIsland_IslandEntrance_EnterBoat_1:
# 101 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	closemessage
# 102 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	release
	return

MythicIsland_IslandEntrance_EnterBoat_2:
# 99 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	warp MAP_MYTHIC_ISLAND_PLAYER_SPAWN, 3, 7
	goto MythicIsland_IslandEntrance_EnterBoat_1


MythicIsland_IslandEntrance_Chimecho::
# 106 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	lock
# 107 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	faceplayer
# 108 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto_if_unset FLAG_MYTHIC_ISLAND_BEACH_CHIMECHO, MythicIsland_IslandEntrance_Chimecho_2
MythicIsland_IslandEntrance_Chimecho_1:
# 116 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	playse SE_M_HEAL_BELL
# 117 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	waitse
# 118 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	special HealPlayerParty
# 119 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_Chimecho_Text_1, MSGBOX_YESNO
# 123 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	compare VAR_RESULT, YES
	goto_if_eq MythicIsland_IslandEntrance_Chimecho_5
# 127 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_IslandEntrance_Chimecho_End
MythicIsland_IslandEntrance_Chimecho_4:
# 130 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
MythicIsland_IslandEntrance_ChimechoTeleport:
# 131 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	dynmultipush MythicIsland_IslandEntrance_Chimecho_Text_2, 0
# 133 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto_if_set FLAG_MYTHIC_ISLAND_SUNKEN_SHRINE_CHIMECHO, MythicIsland_IslandEntrance_Chimecho_9
MythicIsland_IslandEntrance_Chimecho_8:
# 137 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto_if_set FLAG_MYTHIC_ISLAND_LAKE_CHIMECHO, MythicIsland_IslandEntrance_Chimecho_12
MythicIsland_IslandEntrance_Chimecho_11:
# 142 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	dynmultistack 0, 0, TRUE, 4, FALSE, 0, DYN_MULTICHOICE_CB_NONE
# 144 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	switch VAR_RESULT
# 145 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	case 1, MythicIsland_IslandEntrance_Chimecho_16
# 153 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	case 2, MythicIsland_IslandEntrance_Chimecho_17
# 161 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_IslandEntrance_Chimecho_End
MythicIsland_IslandEntrance_Chimecho_14:
# 164 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
MythicIsland_IslandEntrance_Chimecho_End:
# 165 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	closemessage
# 166 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	release
	return

MythicIsland_IslandEntrance_Chimecho_2:
# 109 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	playmoncry SPECIES_CHIMECHO, CRY_MODE_NORMAL
# 110 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	waitmoncry
# 111 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_Chimecho_Text_0
# 114 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	setflag FLAG_MYTHIC_ISLAND_BEACH_CHIMECHO
	goto MythicIsland_IslandEntrance_Chimecho_1

MythicIsland_IslandEntrance_Chimecho_5:
# 124 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_IslandEntrance_ChimechoTeleport
	goto MythicIsland_IslandEntrance_Chimecho_4

MythicIsland_IslandEntrance_Chimecho_9:
# 134 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	dynmultipush MythicIsland_IslandEntrance_Chimecho_Text_3, 1
	goto MythicIsland_IslandEntrance_Chimecho_8

MythicIsland_IslandEntrance_Chimecho_12:
# 138 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	dynmultipush MythicIsland_IslandEntrance_Chimecho_Text_4, 2
	goto MythicIsland_IslandEntrance_Chimecho_11

MythicIsland_IslandEntrance_Chimecho_16:
# 146 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	closemessage
# 147 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	playse SE_M_PSYBEAM
# 148 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, teleportSpin
# 149 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	waitmovement 0
# 150 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, teleportFly
# 151 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	waitmovement 0
# 152 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	warp MAP_MYTHIC_ISLAND_SUNKEN_SHRINE, 13, 62
	goto MythicIsland_IslandEntrance_Chimecho_14

MythicIsland_IslandEntrance_Chimecho_17:
# 154 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	closemessage
# 155 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	playse SE_M_PSYBEAM
# 156 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, teleportSpin
# 157 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	waitmovement 0
# 158 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, teleportFly
# 159 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	warp MAP_MYTHIC_ISLAND_LAKE, 10, 32
	goto MythicIsland_IslandEntrance_Chimecho_14


MythicIsland_IslandEntrance_OmastarMerchant::
# 181 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	lock
# 182 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	faceplayer
# 183 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	playmoncry SPECIES_OMASTAR, CRY_MODE_NORMAL
# 184 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_0
# 188 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
MythicIsland_OmastarShop:
# 189 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	dynmultipush MythicIsland_IslandEntrance_OmastarMerchant_Text_1, 0
# 190 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	dynmultipush MythicIsland_IslandEntrance_OmastarMerchant_Text_2, 211
# 191 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	dynmultipush MythicIsland_IslandEntrance_OmastarMerchant_Text_3, 212
# 192 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	dynmultipush MythicIsland_IslandEntrance_OmastarMerchant_Text_4, 213
# 193 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	dynmultipush MythicIsland_IslandEntrance_OmastarMerchant_Text_5, 214
# 194 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	dynmultipush MythicIsland_IslandEntrance_OmastarMerchant_Text_6, 215
# 195 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	dynmultipush MythicIsland_IslandEntrance_OmastarMerchant_Text_7, 215
# 196 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	dynmultipush MythicIsland_IslandEntrance_OmastarMerchant_Text_8, 216
# 197 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	dynmultipush MythicIsland_IslandEntrance_OmastarMerchant_Text_9, 217
# 198 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	dynmultistack 0, 0, TRUE, 4, FALSE, 0, DYN_MULTICHOICE_CB_SHOW_ITEM
# 199 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	switch VAR_RESULT
# 200 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	case 211, MythicIsland_IslandEntrance_OmastarMerchant_3
# 231 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	case 212, MythicIsland_IslandEntrance_OmastarMerchant_4
# 262 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	case 213, MythicIsland_IslandEntrance_OmastarMerchant_5
# 293 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	case 214, MythicIsland_IslandEntrance_OmastarMerchant_6
# 324 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	case 215, MythicIsland_IslandEntrance_OmastarMerchant_7
# 355 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	case 216, MythicIsland_IslandEntrance_OmastarMerchant_8
# 386 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	case 217, MythicIsland_IslandEntrance_OmastarMerchant_9
# 418 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_OmastarShopEnd
MythicIsland_IslandEntrance_OmastarMerchant_1:
# 421 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
MythicIsland_OmastarShopEnd:
# 422 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_21
# 425 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	closemessage
# 426 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	release
	return

MythicIsland_IslandEntrance_OmastarMerchant_3:
# 201 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	checkitem ITEM_BIG_PEARL
# 202 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	compare VAR_RESULT, 0
	goto_if_ne MythicIsland_IslandEntrance_OmastarMerchant_11
# 226 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_14
# 229 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_OmastarShop
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_4:
# 232 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	checkitem ITEM_BIG_PEARL
# 233 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	compare VAR_RESULT, 0
	goto_if_ne MythicIsland_IslandEntrance_OmastarMerchant_14
# 257 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_14
# 260 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_OmastarShop
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_5:
# 263 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	checkitem ITEM_BIG_PEARL
# 264 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	compare VAR_RESULT, 0
	goto_if_ne MythicIsland_IslandEntrance_OmastarMerchant_17
# 288 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_14
# 291 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_OmastarShop
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_6:
# 294 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	checkitem ITEM_BIG_PEARL
# 295 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	compare VAR_RESULT, 0
	goto_if_ne MythicIsland_IslandEntrance_OmastarMerchant_20
# 319 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_14
# 322 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_OmastarShop
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_7:
# 325 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	checkitem ITEM_BIG_PEARL
# 326 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	compare VAR_RESULT, 0
	goto_if_ne MythicIsland_IslandEntrance_OmastarMerchant_23
# 350 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_14
# 353 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_OmastarShop
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_8:
# 356 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	checkitem ITEM_BIG_PEARL
# 357 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	compare VAR_RESULT, 0
	goto_if_ne MythicIsland_IslandEntrance_OmastarMerchant_26
# 381 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_14
# 384 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_OmastarShop
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_9:
# 387 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	checkitem ITEM_BIG_PEARL
# 388 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	compare VAR_RESULT, 0
	goto_if_ne MythicIsland_IslandEntrance_OmastarMerchant_29
# 412 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_14
# 415 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_OmastarShop
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_11:
# 203 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_10, MSGBOX_YESNO
# 206 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	compare VAR_RESULT, YES
	goto_if_eq MythicIsland_IslandEntrance_OmastarMerchant_32
# 219 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_13
# 222 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_OmastarShop
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_14:
# 234 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_15, MSGBOX_YESNO
# 237 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	compare VAR_RESULT, YES
	goto_if_eq MythicIsland_IslandEntrance_OmastarMerchant_35
# 250 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_13
# 253 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_OmastarShop
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_17:
# 265 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_16, MSGBOX_YESNO
# 268 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	compare VAR_RESULT, YES
	goto_if_eq MythicIsland_IslandEntrance_OmastarMerchant_38
# 281 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_13
# 284 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_OmastarShop
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_20:
# 296 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_17, MSGBOX_YESNO
# 299 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	compare VAR_RESULT, YES
	goto_if_eq MythicIsland_IslandEntrance_OmastarMerchant_41
# 312 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_13
# 315 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_OmastarShop
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_23:
# 327 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_18, MSGBOX_YESNO
# 330 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	compare VAR_RESULT, YES
	goto_if_eq MythicIsland_IslandEntrance_OmastarMerchant_44
# 343 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_13
# 346 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_OmastarShop
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_26:
# 358 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_19, MSGBOX_YESNO
# 361 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	compare VAR_RESULT, YES
	goto_if_eq MythicIsland_IslandEntrance_OmastarMerchant_47
# 374 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_13
# 377 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_OmastarShop
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_29:
# 389 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_20, MSGBOX_YESNO
# 392 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	compare VAR_RESULT, YES
	goto_if_eq MythicIsland_IslandEntrance_OmastarMerchant_50
# 405 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_13
# 408 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	goto MythicIsland_OmastarShop
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_32:
# 207 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	playse SE_SHOP
# 208 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	waitse
# 209 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	giveitem ITEM_FIRE_STONE
# 210 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_11
# 213 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	removeitem ITEM_BIG_PEARL
# 214 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_12
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_35:
# 238 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	playse SE_SHOP
# 239 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	waitse
# 240 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	giveitem ITEM_WATER_STONE
# 241 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_11
# 244 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	removeitem ITEM_BIG_PEARL
# 245 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_12
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_38:
# 269 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	playse SE_SHOP
# 270 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	waitse
# 271 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	giveitem ITEM_LEAF_STONE
# 272 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_11
# 275 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	removeitem ITEM_BIG_PEARL
# 276 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_12
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_41:
# 300 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	playse SE_SHOP
# 301 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	waitse
# 302 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	giveitem ITEM_ICE_STONE
# 303 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_11
# 306 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	removeitem ITEM_BIG_PEARL
# 307 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_12
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_44:
# 331 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	playse SE_SHOP
# 332 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	waitse
# 333 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	giveitem ITEM_SUN_STONE
# 334 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_11
# 337 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	removeitem ITEM_BIG_PEARL
# 338 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_12
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_47:
# 362 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	playse SE_SHOP
# 363 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	waitse
# 364 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	giveitem ITEM_MOON_STONE
# 365 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_11
# 368 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	removeitem ITEM_BIG_PEARL
# 369 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_12
	goto MythicIsland_IslandEntrance_OmastarMerchant_1

MythicIsland_IslandEntrance_OmastarMerchant_50:
# 393 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	playse SE_SHOP
# 394 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	waitse
# 395 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	giveitem ITEM_SHINY_STONE
# 396 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_11
# 399 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	removeitem ITEM_BIG_PEARL
# 400 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	msgbox MythicIsland_IslandEntrance_OmastarMerchant_Text_12
	goto MythicIsland_IslandEntrance_OmastarMerchant_1


MythicIsland_IslandEntrance_Sign_Text_0:
# 88 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "The writing on the sign are barely\n"
	.string "legible.\p"
	.string "“...T...rn b...c...”\n"
	.string "“...Prevent your ...e...th...”$"

MythicIsland_IslandEntrance_EnterBoat_Text_0:
# 96 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Enter your boat?$"

MythicIsland_IslandEntrance_Chimecho_Text_0:
# 112 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Chime...$"

MythicIsland_IslandEntrance_Chimecho_Text_1:
# 120 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "> The soothing chime fills your Pokémon\n"
	.string "with restoration.\p"
	.string "Would you like Chimecho to teleport\n"
	.string "you?$"

MythicIsland_IslandEntrance_Chimecho_Text_2:
# 131 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Cancel$"

MythicIsland_IslandEntrance_Chimecho_Text_3:
# 134 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Flooded Tunnels$"

MythicIsland_IslandEntrance_Chimecho_Text_4:
# 138 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Lake$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_0:
# 185 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Greetings, brave traveler! Care to take\n"
	.string "a look at my shiny rock collection? I'd\l"
	.string "be willing to toss one of them your way,\l"
	.string "for the price of a {COLOR BLUE}Big Pearl{COLOR DARK_GRAY}.$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_1:
# 189 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "I'm good$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_2:
# 190 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Fire Stone$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_3:
# 191 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Water Stone$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_4:
# 192 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Thunder Stone$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_5:
# 193 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Leaf Stone$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_6:
# 194 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Ice Stone$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_7:
# 195 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Sun Stone$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_8:
# 196 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Moon Stone$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_9:
# 197 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Shiny Stone$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_10:
# 204 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Exchange a {COLOR BLUE}Big Pearl{COLOR DARK_GRAY} for a {COLOR BLUE}Fire Stone{COLOR DARK_GRAY}?$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_11:
# 211 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "> You gave 1 {COLOR BLUE}Big Pearl{COLOR DARK_GRAY} in exchange.$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_12:
# 215 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Thanks for the swap! Is there anything\n"
	.string "else you would like?$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_13:
# 220 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "What stone would you like?$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_14:
# 227 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Sorry, I only want a {COLOR BLUE}Big Pearl{COLOR DARK_GRAY} in\n"
	.string "exchange.$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_15:
# 235 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Exchange a {COLOR BLUE}Big Pearl{COLOR DARK_GRAY} for a {COLOR BLUE}Water Stone{COLOR DARK_GRAY}?$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_16:
# 266 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Exchange a {COLOR BLUE}Big Pearl{COLOR DARK_GRAY} for a {COLOR BLUE}Leaf Stone{COLOR DARK_GRAY}?$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_17:
# 297 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Exchange a {COLOR BLUE}Big Pearl{COLOR DARK_GRAY} for an {COLOR BLUE}Ice Stone{COLOR DARK_GRAY}?$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_18:
# 328 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Exchange a {COLOR BLUE}Big Pearl{COLOR DARK_GRAY} for a {COLOR BLUE}Sun Stone{COLOR DARK_GRAY}?$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_19:
# 359 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Exchange a {COLOR BLUE}Big Pearl{COLOR DARK_GRAY} for a {COLOR BLUE}Moon Stone{COLOR DARK_GRAY}?$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_20:
# 390 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Exchange a {COLOR BLUE}Big Pearl{COLOR DARK_GRAY} for a {COLOR BLUE}Shiny Stone{COLOR DARK_GRAY}?$"

MythicIsland_IslandEntrance_OmastarMerchant_Text_21:
# 423 "data/maps/MythicIsland_IslandEntrance/scripts.pory"
	.string "Praise Helix, my friend.$"
